# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    configmap.yaml                                     :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: fngoc <fngoc@student.42.fr>                +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/03/10 10:56:21 by fngoc             #+#    #+#              #
#    Updated: 2021/03/10 10:56:22 by fngoc            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 192.168.99.104-192.168.99.104